### ISSUE TITLE
`max_tokens_to_sample: 9016` - Is this the Anthropic API maximum?

### ISSUE THREAD

**Issue by hhooeezz** [jtsang4/claude-to-chatgpt#18]
This is regarding [this line](https://github.com/jtsang4/claude-to-chatgpt/blob/487ff6eb6811ddaf3336579a8ccdd4ba576ecf0e/cloudflare-worker.js#L169).

We cannot find the `9016` token maximum anywhere in the [Anthropic](https://docs.anthropic.com/claude/reference/complete_post#:~:text=max_tokens_to_sample,tokens%20to%20generate.) or any [third-party](https://autocode.com/anthropic/api/playground/dev/complete/) documentation. The `max_tokens_to_sample` _[is](https://docs.anthropic.com/claude/reference/complete_post#:~:text=integer-,required,-The%20maximum%20number)_ mandatory, though, so we must set _something_ (obviously <<10000).

If there is no hard limit in Anthropic's API, why not explicitly leave it to the script user:

```
// Config constant for max tokens 
const MAX_TOKENS = 9016;

async function handleRequest(request) {

  // ...
  
  const claudeRequestBody = {
    prompt,
    model: claudeModel,
    temperature,
    stop_sequences: stop,
    stream,
    
    // Always include max_tokens, using constant as default
    max_tokens_to_sample: MAX_TOKENS  
  };

  // ...

}
```

Either way, we appreciate having found your nifty script.

**Comment by jtsang4** [comment]
9016 is an empirical value, because Cloudflare Worker only supports API response time within 10ms for free plan. However, this value does not seem to work recently, Proxy API endpoint deployed using Cloudflare Worker now often have the problem of returning truncated. I have adopted the Docker deployment solution myself.  

You are right, this value can be set as a constant for easy modification by those in need, I will extract it.

**Comment by jtsang4** [comment]
The value has been extracted.
